# Generated by Django 3.2.23 on 2023-11-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='keyword',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(to='knowledgebase.Keyword'),
        ),
    ]
