# Generated by Django 4.2.7 on 2023-12-12 17:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledgebase', '0004_remove_comment_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Technique',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='technique',
        ),
    ]
