# Generated by Django 4.2.7 on 2023-12-18 21:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0005_rename_post_technique_rename_post_comment_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[205, None], upload_to='thumbnails/'),
        ),
    ]
