# Generated by Django 4.2.7 on 2023-12-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0006_alter_technique_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='thumbnail_alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
